/*
 * Copyright 2017 Kaidan Gustave
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package xyz.nightfury.html.document

import kotlinx.html.*
import xyz.nightfury.html.DocumentGenerator
import xyz.nightfury.html.extensions.discord
import xyz.nightfury.html.extensions.favicon

/**
 * @author Kaidan Gustave
 */
object Index : DocumentGenerator {
    override val file: String = "index"

    override fun HTML.generate() {
        head {
            meta  { charset = "UTF-8" }
            title { + "NightFury" }

            script { type = "text/javascript"; src = "kotlin.js" }
            script { type = "text/javascript"; src = "kotlinx-html-js.js" }
            script { type = "text/javascript"; src = "main.js" }

            link { rel = "stylesheet"; type = "text/css"; href = "fonts/kung_fu_panda/stylesheet.css" }
            link { rel = "stylesheet"; type = "text/css"; href = "fonts/kingthings_clarity/stylesheet.css" }
            link { rel = "stylesheet"; type = "text/css"; href = "stylesheets/index.css" }

            favicon(base = "/")

            meta {
                name = "keywords"
                content = "discord,bot,nightfury,toothless,moderation,server,dragon,how to train your dragon"
            }

            discord {
                title = "NightFury"
                description = "NightFury is a multipurpose Discord bot for your server! " +
                              "It provides moderation, utility, wide-ranging customization, " +
                              "and other useful features!"
                image = "https://nightfury.xyz/nightfury.jpg"
            }
        }

        body(classes = "index") {
            // This will be generated by the java script.
        }
    }
}