/*
 * Copyright 2017 Kaidan Gustave
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package xyz.nightfury.html.document.error

import kotlinx.html.*
import xyz.nightfury.html.DocumentGenerator
import xyz.nightfury.html.extensions.favicon

/**
 * @author Kaidan Gustave
 */
object Error404 : DocumentGenerator {
    override val file: String
        get() = "404"
    override val subDir: String
        get() = "error"

    override fun HTML.generate() {
        head {
            meta  { charset = "UTF-8" }
            title { + "404 - Not Found" }

            script { type = "text/javascript"; src = "../kotlin.js" }
            script { type = "text/javascript"; src = "../kotlinx-html-js.js" }
            script { type = "text/javascript"; src = "../main.js" }

            favicon()
        }

        body {
            // This will be generated by the java script.
        }
    }

}